### ISSUE TITLE
Call to a member function setTime() on bool

### ISSUE THREAD

**Issue by pcn3rd51** [benhall14/php-calendar#10]
PHP: 8.1.6
Laravel: 10.48.4

This is in my CalendarController:

`$googleEvents = Event::get();
        $calendar = new Calendar();
        $events = array();

        foreach($googleEvents as $row) {
            if(date('Y-m-d') === $row->start->date) {
                $events[] = array(
                    'start'   => $row->start->date ?? $row->start->dateTime,
                    'end'     => $row->end->date ?? $row->end->dateTime,
                    'summary' => $row->summary,
                    'mask'    => true,
                    'classes' => ['alert-secondary']
                );
            } else {
                $events[] = array(
                    'start'   => $row->start->date ?? $row->start->dateTime,
                    'end'     => $row->end->date ?? $row->end->dateTime,
                    'summary' => $row->summary,
                );
            }
        }

        $calendar->addEvents($events);

        return view('calendar', ['calendar' => $calendar, 'weather' => $weather]);`

This is on my blade template:
`{{ $calendar->draw(date('Y-m-d')) }}`

Error Message:
`Call to a member function setTime() on bool`

Highlighted Line:
`$calendar->addEvents($events);`

tried passing a date('Y-m-d H:i:s') with no luck.

**Comment by benhall14** [comment]
Thanks for the message. You need to use the format "Y-m-d H:i" as per the documentation, so something like:

```
foreach($googleEvents as $row) {
        if(date('Y-m-d') === $row->start->date) {
            $events[] = array(
                'start'   => $row->start->date ?? $row->start->dateTime->format('Y-m-d H:i'),
                'end'     => $row->end->date ?? $row->end->dateTime->format('Y-m-d H:i'),
                'summary' => $row->summary,
                'mask'    => true,
                'classes' => ['alert-secondary']
            );
        } else {
            $events[] = array(
                'start'   => $row->start->date ?? $row->start->dateTime->format('Y-m-d H:i'),
                'end'     => $row->end->date ?? $row->end->dateTime->format('Y-m-d H:i'),
                'summary' => $row->summary,
            );
        }
    }

    $calendar->addEvents($events);

    return view('calendar', ['calendar' => $calendar, 'weather' => $weather]);
```

Or passing a date like date('Y-m-d H:i')

Thanks,
Ben
