### ISSUE TITLE
Highlighting todays date on the calendar

### ISSUE THREAD

**Issue by pcn3rd51** [benhall14/php-calendar#11]
PHP 8.1
Laravel 10.x

im trying to pull all my google events into the calendar and was able to do that but now im tying to highlight todays date. i thought the mask and class would work but its only when an event is on todays date. is there an option im overlooking?

in my controller:
` $googleEvents = Event::get();
        $calendar = new Calendar();
        $events = array();

        foreach($googleEvents as $row) {
            $startDate = $row->start->date ?? $row->start->dateTime;
            $endDate = $row->end->date ?? $row->end->dateTime;

            if(date('Y-m-d') == date_format(date_create($startDate), 'Y-m-d')) {
                $events[] = array(
                    'start'   => date_format(date_create($startDate), 'Y-m-d'),
                    'end'     => date_format(date_create($endDate), 'Y-m-d'),
                    'summary' => '<div>' . $row->summary . '</div>',
                    'mask'    => true,
                    'classes' => ['bg-danger']
                );
            } else {
                $events[] = array(
                    'start'   => date_format(date_create($startDate), 'Y-m-d'),
                    'end'     => date_format(date_create($endDate), 'Y-m-d'),
                    'summary' => '<div>' . $row->summary . '</div>',
                );
            }
        }

        $calendar->useFullDayNames();
        $calendar->addEvents($events);
`

in my blade:
`{!! $calendar->draw(date('Y-m-d')) !!}`

![image](https://github.com/benhall14/php-calendar/assets/7594266/8a9e933c-c028-48a0-863b-11e3d3b691b1)

**Comment by benhall14** [comment]
From what you have pasted, I can't see an issue. You aren't setting any classes on any events that aren't 'Todays' date, so it's likely the default class used by the calendar doesn't have a CSS style in your custom theme.

Thanks,
Ben
