### ISSUE TITLE
Title attribute on events doesn't escape HTML tags

### ISSUE THREAD

**Issue by pascalchevrel** [benhall14/php-calendar#4]
Hi,

First of all thanks for your library :)

I got a user reporting a bug to me which is that the tooltips that appear when hovering over an event has escaped HTML displayed if the event has html injected in it (in my case, a \<br\> line break). See the screenshot:

![image](https://user-images.githubusercontent.com/454375/229558193-7ea69551-2e5a-4efe-be08-0a193e44db3f.png)

I have a local patch, I'll make a PR.

Cheers
Pascal

**Comment by benhall14** [comment]
Thanks for updating this :)
